import { SigningCosmWasmClient } from "@cosmjs/cosmwasm-stargate";
import { getSigningClient, getAddressFromMnemonic } from "./xionConnect";
import config from "./config";

interface ClaimInfo {
  asset: {
    native?: { denom: string };
    cw20?: { contract: string };
  };
  to: string;
  value: string;
  deadline: number;
  comment: string;
}

/**
 * Example: Claim tokens from the TradeOS contract
 * 
 * Note: This requires a valid signature from the verifier.
 * The signature must be generated off-chain using the verifier's private key.
 * 
 * To get the claim digest, use the queryClaimDigest script first.
 */
async function claim() {
  try {
    // Validate configuration
    config.validateConfig();

    console.log("🔐 Connecting to Xion testnet to claim tokens...");

    // Get sender address
    const senderAddress = await getAddressFromMnemonic(config.OWNER_MNEMONIC!);
    console.log(`📍 Sender wallet address: ${senderAddress}`);

    // Create signing client
    const client = await getSigningClient();

    console.log(`🔗 Connected to ${config.XION_RPC_URL}`);
    console.log(`📜 Contract address: ${config.CONTRACT_ADDRESS}`);

    // Example claim info
    // Note: In production, you would get this from your backend/verifier
    const claimInfo: ClaimInfo = {
      asset: {
        native: { denom: "uxion" },
      },
      to: senderAddress, // Recipient address
      value: "1000000", // 1 XION (in uxion)
      deadline: 0, // 0 = no deadline
      comment: "Example claim from node script",
    };

    // Example signature (must be generated by verifier)
    // WARNING: This is just an example. You need a real signature from the verifier.
    // The signature should be generated using the verifier's private key and the claim digest.
    const signature = "0x" + "0".repeat(128); // Placeholder - replace with actual signature

    console.log("\n📝 Claim Info:");
    console.log(`- Asset: ${JSON.stringify(claimInfo.asset)}`);
    console.log(`- To: ${claimInfo.to}`);
    console.log(`- Value: ${claimInfo.value} uxion`);
    console.log(`- Deadline: ${claimInfo.deadline === 0 ? "No deadline" : new Date(claimInfo.deadline * 1000).toISOString()}`);
    console.log(`- Comment: ${claimInfo.comment}`);

    // First, query the claim digest to verify
    console.log("\n🔍 Querying claim digest...");
    const digestResponse = await client.queryContractSmart(config.CONTRACT_ADDRESS, {
      get_claim_digest: {
        claim: claimInfo,
      },
    });
    console.log(`📋 Claim digest: ${digestResponse.digest_hex}`);

    // Check if already claimed
    console.log("\n🔍 Checking if already claimed...");
    const isClaimedResponse = await client.queryContractSmart(config.CONTRACT_ADDRESS, {
      is_claimed: {
        digest_hex: digestResponse.digest_hex,
      },
    });
    if (isClaimedResponse.claimed) {
      console.log("❌ This claim has already been claimed!");
      return;
    }
    console.log("✅ Claim is available");

    console.log("\n💸 Executing claim transaction...");
    console.log("⚠️  WARNING: Using placeholder signature. Replace with actual signature from verifier!");

    // Execute claim
    const executeMsg = {
      claim: {
        claim: claimInfo,
        signature: signature,
      },
    };

    const fee = "auto";
    const result = await client.execute(
      senderAddress,
      config.CONTRACT_ADDRESS,
      executeMsg,
      fee
    );

    console.log("\n✅ Claim transaction successful!");
    console.log(`📋 Transaction hash: ${result.transactionHash}`);
    console.log(`⛽ Gas used: ${result.gasUsed}`);
    console.log(`📊 Height: ${result.height}`);

    // Verify claim was processed
    console.log("\n🔍 Verifying claim...");
    const verifyResponse = await client.queryContractSmart(config.CONTRACT_ADDRESS, {
      is_claimed: {
        digest_hex: digestResponse.digest_hex,
      },
    });
    console.log(`✅ Claim status: ${verifyResponse.claimed ? "CLAIMED" : "NOT CLAIMED"}`);

  } catch (error: any) {
    console.error("❌ Error:", error.message);
    if (error.stack) {
      console.error("📍 Stack trace:", error.stack);
    }

    // Handle specific error cases
    if (error.message.includes("insufficient funds")) {
      console.error("💰 Insufficient funds. Make sure your wallet has enough tokens.");
    } else if (error.message.includes("contract")) {
      console.error("📜 Contract error. Check if the contract address is correct.");
    } else if (error.message.includes("OWNER_MNEMONIC")) {
      console.error("🔑 Please set OWNER_MNEMONIC in your .env file");
    } else if (error.message.includes("already claimed")) {
      console.error("🔴 This claim has already been claimed.");
    } else if (error.message.includes("signature")) {
      console.error("✍️  Signature verification failed. Make sure you have a valid signature from the verifier.");
    }
  }
}

// Execute the function
claim();

