// Note: cw-multi-test 3.0.0 requires cosmwasm-std 3.x, but we use 2.2.2
// This may cause version conflicts. Tests may need adjustment or use cw-multi-test 2.5.1
// when available in the registry.
use cosmwasm_std::{coins, Addr};
use cw_multi_test::{App, Contract, ContractWrapper, Executor, IntoAddr};
use tradeos_cw_sc::msg::InstantiateMsg;

// Constants for testing
pub const DENOM: &str = "uxion";
pub const INITIAL_BALANCE: u128 = 1000000;

// Helper function to generate a test secp256k1 public key (33 bytes)
pub fn generate_test_pubkey() -> String {
    // This is a test public key in hex format (33 bytes compressed)
    // In real scenarios, this would be generated from a private key
    "0x02a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c".to_string()
}

// Helper function to generate a test signature (64 bytes)
pub fn generate_test_signature() -> String {
    // This is a test signature in hex format (64 bytes: r||s)
    // In real scenarios, this would be generated by signing the digest
    let mut sig = "0x".to_string();
    for _ in 0..64 {
        sig.push_str("a1");
    }
    sig
}

// Contract wrapper for multitest
fn contract_vault() -> Box<dyn Contract<cosmwasm_std::Empty>> {
    let contract = ContractWrapper::new(
        |deps, env, info, msg| tradeos_cw_sc::execute::execute(deps, env, info, msg).map_err(|e| e.into()),
        |deps, env, info, msg| tradeos_cw_sc::contract::instantiate(deps, env, info, msg).map_err(|e| e.into()),
        |deps, env, msg| tradeos_cw_sc::query::query(deps, env, msg),
    );
    Box::new(contract)
}

// Main setup function to deploy contracts and initialize test environment
pub fn setup_contract(app: &mut App, verifier_pubkey: Option<String>) -> Addr {
    // Create test accounts with proper bech32 addresses
    let admin = "admin".into_addr();
    let user1 = "user1".into_addr();
    let user2 = "user2".into_addr();

    // Fund accounts
    app.init_modules(|router, _api, storage| {
        router
            .bank
            .init_balance(storage, &admin, coins(INITIAL_BALANCE, DENOM))
            .unwrap();
        router
            .bank
            .init_balance(storage, &user1, coins(INITIAL_BALANCE, DENOM))
            .unwrap();
        router
            .bank
            .init_balance(storage, &user2, coins(INITIAL_BALANCE, DENOM))
            .unwrap();
    });

    // Deploy vault contract
    let contract_id = app.store_code(contract_vault());
    let msg = InstantiateMsg {
        owner: Some(admin.to_string()),
        verifier_pubkey: verifier_pubkey.unwrap_or_else(generate_test_pubkey),
    };

    let contract_addr = app
        .instantiate_contract(
            contract_id,
            admin.clone(),
            &msg,
            &[],
            "tradeos-vault",
            Some(admin.to_string()),
        )
        .unwrap();

    contract_addr
}

